config/routes.rb
Rails.application.routes.draw do
  root to: "business_applications#index"

  get 'business_applications/allapprovedapplications', to: "business_applications#allapprovedapplications", approved: true

  resources :business_applications
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/business_application.rb
class BusinessApplication < ApplicationRecord
    validates :title, presence: true
    validates :about, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/business_applications_controller.rb
class BusinessApplicationsController < ApplicationController

  def index
    @business_application = BusinessApplication.all
  end

  def allapprovedapplications
    @business_application = BusinessApplication.where(:status => 1)
  end

  def new
    @business_application = BusinessApplication.new
  end

  def show
    @business_application = BusinessApplication.find(params[:id])
  end

  def edit
    @business_application = BusinessApplication.find(params[:id])
  end

  def update
    @business_application = BusinessApplication.find(params[:id])
    respond_to do |format|
      if @business_application.update(business_application_params)
        flash[:success] = "Application updated!" 
        format.html { redirect_to root_path}
        format.json { head :no_content }
      else
        flash.now[:danger] = "Failed to update application"
        render :edit 
      end
    end
  end

  def create
    @business_application = BusinessApplication.new(business_application_params)

    if @business_application.save   
      flash[:success] = "Application created!" 
      redirect_to root_path
    else
      flash.now[:danger] = "Failed to create application"
      render :new
    end
  end


  def destroy  
    @business_application = BusinessApplication.find(params[:id])
    respond_to do |format|
      if @business_application.destroy
        flash[:success] = "Application deleted!" 
        format.html { redirect_to root_path}
        format.json { head :no_content }
      else
        flash.now[:danger] = "Failed to delete applicationn"
        render :edit 
      end
    end
  end

  private 
  
  def business_application_params
    params.require(:business_application).permit(:title,:about,:status)
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/business_applications_helper.rb
module BusinessApplicationsHelper

    def active_class(link_path)
        current_page?(link_path) ? "active" : ""
    end
end

app/views/business_applications/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark rounded-0">
  <%= link_to 'Business Applications', root_path, class:'navbar-brand'  %>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
        <li class="<%= active_class('/') %>">
          <%= link_to 'Home', root_path, class:'nav-item nav-link'  %>
        </li>

        <li class="<%= active_class('/business_applications/new') %>">
          <%= link_to 'Create Application', new_business_application_path, class:'nav-item nav-link'  %>
        </li>

        <li class="<%= active_class('/business_applications/allapprovedapplications') %>">
          <%= link_to 'All Approved Applications', business_applications_allapprovedapplications_path, class:'nav-item nav-link'  %>
        </li>
    </div>
  </div>
</nav>

app/views/business_applications/allapprovedapplications.html.erb
<h1 class="text-left"><strong>All Approved Business Applications</strong></h1>
<br/>
<table class="table table-striped table-hover">
    <thead class="thead-dark">
    <tr>
        <th>Business Name</th>
        <th>Application Created</th>
        <th>Status</th>
        <th class="text-right">Time Approved</th>
    </tr>
    </thead>

    <tbody>
    <% @business_application.each do |app| %>
        <tr>

            <td><%= link_to app.title, business_application_path(app)%></td>

            <td><%= app.created_at%></td>

            <% if app.status === 1  %>
                <td class="approve">Approved <i class="fa-solid fa-circle-check"></i></td>
            <% end %>

            <td class="text-right"><%= app.updated_at%></td>

        </tr>
    <% end %>
    </tbody>
</table>

app/views/business_applications/edit.html.erb
<div>

    <h1 class="text-left"><strong><%= @business_application.title %></strong></h1>

    <% flash.each do |key, message| %> 
        <div class="text-center alert alert-<%= key %>">
        <%= message %> 
        </div>
    <% end %>

    <h2>Business Details:</h2>
    <p class="details">
        <%= @business_application.about %> 
    </p>
    <br/>

    <% if @business_application.status == 0 || @business_application.status.nil? %>
        <p class="details">Current Status: <span class="pend">Pending</span></p>
    <% end %>

    <% if @business_application.status == 1 || @business_application.status.nil? %>
        <p class="details">Current Status: <span class="approve">Approved</span></p>
    <% end %>


    <% if @business_application.status == 2 || @business_application.status.nil? %>
        <p class="details">Current Status: <span class="reject">Rejected</span></p>
    <% end %>



    <br/>


    <%= form_with(model: @business_application, local: true) do |f| %>


        <%= f.label :status,  value:'Change Application Status:' %>
        <%= f.select :status, [["Pending","0"], ["Approved","1"], ["Rejected","2"]], {}, {class: "form-control"} %>
    
        <br/>
        <div class="d-flex flex-row justify-content-center gap-3">
            <%= link_to 'Cancel',root_path, class:"smallbutton" %>
            <%= f.submit value:'Change Status' ,class:'smallbutton' %>
            <%= link_to "Delete Application", business_application_path(@business_application.id), class: "deletebutton", data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
            }%>
        </div>
    <% end %>


    
</div>

app/views/business_applications/index.html.erb
<h1 class="text-left"><strong>All Applications</strong></h1>
<br/>
<br/>
<%= link_to "New Application", new_business_application_path ,class:"smallbutton pull-right"%>

<% flash.each do |key, message| %> 
    <div class="text-center home-alert alert alert-<%= key %>">
    <%= message %> 
    </div>
<% end %>
<br/>
<br/>
<table class="table table-striped table-hover">
    <thead class="thead-dark">
    <tr>
        <th>Business Name</th>
        <th>Application Created</th>
        <th>Status</th>
        <th></th>
    </tr>
    </thead>

    <tbody>
    <% @business_application.each do |app| %>
        <tr>

            <td><%= app.title%></td>

            <td><%= app.created_at%></td>

            <% if app.status == 0 || app.status.nil? %>
                <td class="pend" >Pending <i class="fa-regular fa-circle-dot"></i></td>
            <% end %>

            <% if app.status === 1  %>
                <td class="approve">Approved <i class="fa-solid fa-circle-check"></i></td>
            <% end %>

            <% if app.status === 2  %>
                <td class="reject">Rejected <i class="fa-solid fa-circle-xmark"></i></td>
            <% end %>

            <td class="text-right"><%= link_to 'Edit Status', edit_business_application_path(app)%></td>
            
        </tr>
    <% end %>
    </tbody>
</table>

app/views/business_applications/new.html.erb
<div>

    <% flash.each do |key, message| %> 
        <div class="text-center alert alert-<%= key %>">
        <%= message %> 
        </div>
    <% end %>

    <h1 class="text-center"><strong>Add New Business Application</strong></h1>
    
    <div>
        <%= form_for(@business_application, :html => {'data-turbo' => "false", class: "form-horizontal", role: "form"}) do |f| %>
            <%if @business_application.errors.any? %>
                <div class="errorbox">
                    <p>The form cannot be submitted without changing the following:</p>
                    <% @business_application.errors.full_messages.each do |errormsg| %>
                        <%= errormsg %>
                        <br/>
                    <% end %>
                </div>
            <% end %>
            
            <div class="formfields">

                <div>
                    <label>Business Title</label>
                    <%= f.text_field :title, class:'form-control',  autofocus: true  %>
                </div>

                <div>
                    <label>Business Details</label>
                    <%= f.text_area :about, class:'form-control',  autofocus: true  %>
                </div>

                <%= f.hidden_field :status, value: 0 %>
                <%= f.submit  value:'Add Application', class:'submitbtn pull-left smallbutton '%>
            </div>
        <% end %>
    </div>

</div>

app/views/business_applications/show.html.erb
<div>

    <h1 class="text-left"><strong><%= @business_application.title %></strong></h1>

    <h2>Business Details:</h2>
    <p class="details">
        <%= @business_application.about %> 
    </p>
    <br/>

    <% if @business_application.status == 0 || @business_application.status.nil? %>
        <p class="details">Current Status: <span class="pend">Pending</span></p>
    <% end %>

    <% if @business_application.status == 1 || @business_application.status.nil? %>
        <p class="details">Current Status: <span class="approve">Approved</span></p>
    <% end %>

    <% if @business_application.status == 2 || @business_application.status.nil? %>
        <p class="details">Current Status: <span class="reject">Rejected</span></p>
    <% end %>

    <br/>
    <%= link_to 'Back',business_applications_allapprovedapplications_path, class:"smallbutton" %>

    <br/>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Business Applications</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'business_applications/header' %>
      <div  class="container">
        <%= yield %>
      </div>

      <br/>
  </body>

</html>